import sqlite3
import pandas as pd
import os

def build_database():
    db_file = 'lawgic.db'
    csv_file = 'bns_laws.csv' # This now contains the full parsed text

    if os.path.exists(db_file):
        os.remove(db_file)
        print("Old database removed.")

    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS laws (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            section TEXT NOT NULL,
            description TEXT NOT NULL,
            pos_precedent TEXT,
            neg_precedent TEXT
        )
    ''')

    try:
        # Load the CSV generated by the parser
        df = pd.read_csv(csv_file)
        df.fillna("Not available", inplace=True)
        
        for index, row in df.iterrows():
            cursor.execute('''
                INSERT INTO laws (section, description, pos_precedent, neg_precedent)
                VALUES (?, ?, ?, ?)
            ''', (row['section'], row['description'], row['pos_precedent'], row['neg_precedent']))
            
        conn.commit()
        print(f"Success! Lawgic is now powered by {len(df)} BNS sections.")
        
    except Exception as e:
        print(f"Error: {e}")
    finally:
        conn.close()

if __name__ == '__main__':
    build_database()